[info]
game-name = "WW:GZ"
full-game-name = "The Legend of Zelda: The Wind Waker Debug"
developer-name = "The Wind Waker Community"
full-developer-name = "Wind Waker Speedrun Community"

[src]
iso = "gzlj01.iso"
patch = "src/patch.asm"
map = "maps/framework.map"

[build]
map = "target/framework.map"
iso = "target/rom_hack.iso"

[link]
entries = ["init", "game_loop", "read_controller", "draw"]
base = "0x8040_1000"
