[info]
game-name = "Wind Waker: Debug Menu"
full-game-name = "Wind Waker: Debug Menu"
developer-name = "The Wind Waker Community"
full-developer-name = "Wind Waker Speedrun Community"
description = "Allows for more control over the game"
image = "banner.png"

[src]
iso = "gzlj01.iso"
patch = "src/patch.asm"
map = "maps/framework.map"

[build]
map = "target/framework.map"
iso = "target/rom_hack.iso"

[link]
entries = ["init", "game_loop", "read_controller", "draw"]
base = "0x8040_1000"
